### ISSUE TITLE
Open in Autocode link fails.

### ISSUE THREAD

**Issue by steveruizok** [acode/copenhagen#1]
Congrats on the launch!

In the README, the button to Open in Autocode leads to an error page. 

![image](https://user-images.githubusercontent.com/23072548/111444895-c2a1cc80-8702-11eb-88ae-9cf8595754d2.png)

![image](https://user-images.githubusercontent.com/23072548/111444968-d4836f80-8702-11eb-8f87-d21bae70ba89.png)

**Comment by keithwhor** [comment]
Thanks for the catch! This has been fixed. Let me know if you encounter any other problems! :)
