### ISSUE TITLE
AltGraphic and OS key are displayed when typing inside editor

### ISSUE THREAD

**Issue by thomas-sim** [acode/copenhagen#2]
Hey !

Lovely project going on here. I've however stumbled accross a quite problematic issue : when I'm typing, if I hit AltGraphic (used a lot on french keyboard) or my OS key, Copenhagen Editor writes "AltGraph" and "OS" which makes the editor pretty much unuasble.

I'm on debian buster with firefox 78.8

**Comment by keithwhor** [comment]
I pushed a fix:

https://github.com/acode/copenhagen/commit/8d536e41ab1806d44b2569ec34baca84878d3ec2

It should be live on https://copenhagen.autocode.com, can you verify? I'll close for now, but if not fixed please LMK.
