### ISSUE TITLE
Editor inserts "Control" and "Alt" strings when you press those keys on Firefox

### ISSUE THREAD

**Issue by marijnh** [acode/copenhagen#4]
Tested on Firefox 86 Linux. Problem doesn't occur for me in Chrome.

A similar problem occurs when I try to do composition, in which case it keeps inserting "Process" instead. That problem _does_ occur on Chrome, but there it inserts "Unidentified".

(Congrats on getting the overlaid-textarea approach to work so well. This looks a lot more solid than similar projects I've seen before.)

**Comment by keithwhor** [comment]
Thanks! I'll look into this later today (tonight). The fix is probably here;

https://github.com/acode/copenhagen/blob/1272792ad6815c2f812b2e3742e7dff7feff1d40/src/Controls/CPHEditor/CPHEditor.js#L788

Adding `key.startsWith('control') || key.startsWith('alt') || key === 'unidentified'` will probably work.

**Comment by keithwhor** [comment]
Also this is similar to;
https://github.com/acode/copenhagen/issues/2

I think I have two code branches that do the same thing in that `if` block, so I'll look at merging them.

**Comment by marijnh** [comment]
Might be worth moving away from directly using the keydown handler for text input, since it won't be possible to support composition/[IME](https://developer.mozilla.org/en-US/docs/Glossary/Input_method_editor) this way, and you'll have an endless list of corner cases like this to catch. Since you already have a focused textarea, it should be possible to let native text input go through and read it from there.

**Comment by keithwhor** [comment]
So we actually already supported IME via the `input` event for things like emoji insertion, but we were running into a corner case in Android as well where keyboard swipes wouldn't populate the `e.key` parameter. So your suggestion is certainly the best course of action. :)

I went ahead and (1) covered the Firefox corner cases you outlined in the `keydown` handler, and then (2) allowed anything not caught + handled in `keydown` to default to the `input` handler. Code updated here:

https://github.com/acode/copenhagen/commit/6c80053acdd1e1326e127505938570081ba8e6e3

I'm closing for know, but feel free to re-open if you have more issues!
