### ISSUE TITLE
Svelte usage

### ISSUE THREAD

**Issue by countnazgul** [acode/copenhagen#6]
First of all want to say that Copenhagen looks and feels great! Thanks!

Im trying to use it in Svelte but facing small issue 

In general I can init the editor and see it on the page. The problem is that the text is not visible for some reason

![image](https://user-images.githubusercontent.com/22850/112884429-6908ad00-90c7-11eb-8230-afba3cf0912c.png)

Found out that the text is there but its too far on the right and thats the reason why is not visible. If I disable `width: 10000px` in the css then the text is visible:

![image](https://user-images.githubusercontent.com/22850/112884770-cdc40780-90c7-11eb-9685-e61591e65cbf.png)

Can you please help me? (hopefully/most likely im doing something wrong)

**Comment by keithwhor** [comment]
Is there a Svelte class above this that's changing the behavior of that CSS class? Can you get the raw HTML + Vanilla JavaScript version working alright?

**Comment by countnazgul** [comment]
Ah found the issue. I knew it was something on my end :)

The main div, containing the editor div, have css applied `text-align: center;`. Once i've commented it the text appeared on the left

```html
<script>
  let editorContainer;

  $: if (editorContainer) {
    let editor = new Copenhagen.Editor({ language: "javascript" });
    editor.open(editorContainer, false);
    editor.setValue("var message = `hello world`;");
  }
</script>

<div class="main">
  <div bind:this={editorContainer} />
</div>

<style>
  .main {
    text-align: center; /* this have to be commented */
    margin: 0 auto;
  }
</style>
```

The vanilla one works fine. Running everything on Windows 10 with Chrome 89.0.4389.90

**Comment by keithwhor** [comment]
Awesome. I'll add a `text-align: left` to the main component later today to prevent this issue, then I'll close afterwards!

**Comment by keithwhor** [comment]
Apologies for the delay! This has been fixed in https://github.com/acode/copenhagen/commit/3b9ef1f36c58372f38aa699ceb38c07944e898b9

Also made some minor CSS styling support fixes :)

**Comment by countnazgul** [comment]
Thank you very much!
